### ISSUE TITLE
Enhance: 增加分享计数

### ISSUE THREAD

**Issue by xqbumu** [airdb/sls-bbhj#10]
分享后用要求前端用share_key调用该接口，在share_key生成时放redis，或者简单加个密码，验证是否在缓存中或者是否合法，OK时，则参考展示数调用下IncreaseShare。
建议用加密方式，那么就可以不用redis了，而且应该更合理一些。加密key应该放在环境变量里。
同一个用户可以设定单日最高分享次数。那么该数据则需要放redis。具体可以逐步实现，在commit里说明具体实现到什么步骤。

单个share_key只给shareCount暂时计数3次先。

tips: 加密key放环境变量里。代码通过PR提交方便审核。

代码切入点:
https://github.com/airdb/sls-mina/blob/main/internal/controller/lost.go#L129

**Comment by seosite** [comment]
1
